### ISSUE TITLE
Misleading neutralino benchmarks.

### ISSUE THREAD

**Issue by pegvin** [Elanis/web-to-desktop-framework-comparison#323] opened 2023-01-12 13:21 UTC
the RAM & CPU usage of neutralinojs apps in the benchmarks only represents the main executable's resource usage, but the main executable of neutralino is only responsible for connecting the webview framework to the low level operations like file IO.

neutralino itself doesn't do any sort of rendering and executing js code, instead it uses the available webview runtime which in many cases performs worse than electron. you need to include the CPU & RAM usage of the child webview process spawned via neutralino or else it just makes no sense to include benchmark of a app which only connects the webview and low level operations.

**Comment by Elanis** [comment] 2023-01-12 13:55
Hi,

Indeed, as we noted in #250 , there are better ways to measure RAM usage, atm, it's accurate only for OS/tech where rendering processes are child processes.

I want to improve this but hadn't enough time yet ...

**Comment by Elanis** [comment] 2023-01-12 13:56
I'm closing this as a duplicate of #250

**Closed by Elanis** 2023-01-12 13:56 UTC
